language: node_js
node_js: 'node'
cache:
  directories:
    - node_modules
notifications:
  email: false
install:
  - npm install
script:
  - npm run lint
  - make dist
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
